### ISSUE TITLE
Add language parameter for get operations/pending endpoint

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-tests#261]
Allow test server to simulate mobile app with specific language. Add an optional parameter locale and use it as a parameter `locale` when calling the enrollment server to get a list of the pending operations.

**Comment by banterCZ** [comment]
To be tested by @zcgandcomp or @kopovan

**Comment by kopovan** [comment]
QA OK

Tested in the oneID env. `https://oneid.wultra.app/powerauth-cloud` and Swagger: https://pa-test-shared-weu-oneid-testserver-app-01.azurewebsites.net/powerauth-test-server/swagger-ui/index.html#/operations-controller/fetchOperations

Data prepration:
1. I have added the SK template to the oneID database and ensured that templates are available for both Czech (cs) and English (en) languages
2. To test this addition, I followed the manual: https://wultra.atlassian.net/wiki/spaces/WULTRA/pages/2394128402/How+to+Onboard+to+Testserver, then I sent an operations request using Postman
3. Then I call an EP: `https://pa-test-shared-weu-oneid-testserver-app-01.azurewebsites.net/powerauth-test-server/operations/pending `
![image](https://github.com/wultra/powerauth-tests/assets/135111051/2c4637e1-6b56-4271-b573-7d6cc3a58a48)
4. The language of the response follows the order described in this ticket: https://github.com/wultra/enrollment-server/issues/891#issuecomment-1776607501, an example of the response is provided below:
```
{
  "status": "OK",
  "responseObject": [
    {
      "id": "af5e3c50-b2b9-45bd-b24f-a922faa6dc90",
      "name": "payment",
      "data": "A1*A100.00EUR*Q${account}",
      "operationCreated": "2023-11-08T10:49:39.000+00:00",
      "operationExpires": "2023-11-08T10:54:39.000+00:00",
      "allowedSignatureType": {
        "type": "2FA",
        "variants": [
          "possession_knowledge",
          "possession_biometry"
        ]
      },
      "formData": {
        "title": "Payment Approval",
        "message": "Please confirm the payment",
        "attributes": [
          {
            "type": "AMOUNT",
            "id": "operation.amount",
            "label": "Amount"
          },
          {
            "type": "KEY_VALUE",
            "id": "operation.iban",
            "label": "To Account"
          }
        ]
      }
    },
    {
      "id": "f7ac5bf6-6db3-43e4-9d95-f0896fd72d42",
      "name": "ps_login",
      "data": "A0*T999*TSlovenská republika*T17.10.2023, 14:56:48",
      "operationCreated": "2023-11-08T10:49:07.000+00:00",
      "operationExpires": "2023-11-08T11:39:07.000+00:00",
      "allowedSignatureType": {
        "type": "2FA",
        "variants": [
          "possession_knowledge",
          "possession_biometry"
        ]
      },
      "formData": {
        "title": "Potvrdenie prihlásenia",
        "message": "Pokúšate sa prihlásiť do účtu Pluso?\n    Obdržali sme požiadavku na prihlásenie sa do účtu Pluso. Nepotvrdzujte požiadavku, ak sa nezhoduje ID požiadavky, alebo ak o ňu požiadal niekto cudzí.",
        "attributes": [
          {
            "type": "KEY_VALUE",
            "id": "operation.operation_id",
            "label": "ID požiadavky "
          },
          {
            "type": "KEY_VALUE",
            "id": "operation.country",
            "label": "Krajina "
          },
          {
            "type": "KEY_VALUE",
            "id": "operation.time",
            "label": "Čas "
          }
        ]
      }
    }
  ]
}
```
