### ISSUE TITLE
FIDO2 Test: Pass excludeCredentials list from challenge response

### ISSUE THREAD

**Issue by jnpsk** [wultra/powerauth-tests#428]

**Comment by kopovan** [comment]
after I tried to register the same user again it fails

![image](https://github.com/wultra/powerauth-tests/assets/135111051/edb6792e-4b8a-41ef-bb58-435fcc530e5b)
![image](https://github.com/wultra/powerauth-tests/assets/135111051/4a4b2d49-6671-4391-8f74-859d13e3b909)
