### ISSUE TITLE
FIDO2 Test: User details input options

### ISSUE THREAD

**Issue by jnpsk** [wultra/powerauth-tests#430]
FIDO2 Test web app should allow to input User ID, Username and Display Name

**Comment by kopovan** [comment]
Before state: 
![Snímek obrazovky 2024-05-03 v 10 58 31](https://github.com/wultra/powerauth-tests/assets/135111051/7707047e-b257-489a-aabb-82ccf041e235)
After state: 
![Snímek obrazovky 2024-05-03 v 10 58 38](https://github.com/wultra/powerauth-tests/assets/135111051/90e19a74-19d2-429d-957c-f00dc50c14d3)
![Snímek obrazovky 2024-05-03 v 11 08 51](https://github.com/wultra/powerauth-tests/assets/135111051/2083a409-249f-4e32-a55c-b5c5a342707a)
![image](https://github.com/wultra/powerauth-tests/assets/135111051/835ac17c-7178-45fe-a25b-22a857ec1700)

![image](https://github.com/wultra/powerauth-tests/assets/135111051/892c5e66-3140-4f44-8759-6456560792ef)
![image](https://github.com/wultra/powerauth-tests/assets/135111051/92fef72d-0570-4b94-a1f5-345988b5e838)
