### ISSUE TITLE
Make the code more compact by using modern Java APIs

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-tests#445]

**Comment by zcgandcomp** [comment]
@korbelm deploy please on OneID and run robot. Close if Robot is green.

**Comment by korbelm** [comment]
Robot has issues with some tests with error:

Dictionary '${response}' has no key 'tokenId'.

https://github.com/wultra/testing/actions/runs/9174854515

**Comment by banterCZ** [comment]
👀 @korbelm I merged it now. Could you deploy and run robot tests again, please?

**Comment by korbelm** [comment]
does not look like any improvement ( maybe it got broken before this PR)

**Comment by banterCZ** [comment]
It is a different error. This will be fixed by #454

**Comment by korbelm** [comment]
Robot is green now with OneID 1.7.1 and latest 1.8 testserver
